### ISSUE TITLE
Fix Storybook "addons"

### ISSUE THREAD

**Issue by Kristina456** [Kristina456/Login-form#5]
storybook-preset-craco isn’t configured correctly. It looks like the code from the package README was just copy/pasted over without context :) Right now, your .storybook/main.js exports an object with two “addons” arrays, the latter overriding the former. This is the reason why story controls and other features aren’t appearing in Storybook. Merge the two “addons” arrays together to fix this. And if you’re unsure how Storybook configurations work, check out the Storybook docs https://storybook.js.org/docs/react/configure/overview#configure-your-storybook-project

**Comment by dstrekelj** [comment]
The fix looks good 👍 

I noticed you have it set up in a separate branch ([Login-form/bugfix/#5_storybook_addons](https://github.com/Kristina456/Login-form/tree/bugfix/%235_storybook_addons)). Feel free to merge it into the dev branch.
